import type { EvidenceLevel } from "@/lib/content";
import type { ArticleLocale } from "@/lib/i18n";

const chromeLabels: Record<ArticleLocale, Record<string, string>> = {
  en: {},
  de: {
    Home: "Startseite", Platforms: "Plattformen", "Purchase & PC": "Kauf & PC", Price: "Preis", "Free to Play": "Kostenlos spielen", "Release Date": "Veröffentlichung", "System Requirements": "Systemanforderungen", Consoles: "Konsolen", "Console Guide": "Konsolen-Guide", "Xbox & Game Pass": "Xbox & Game Pass", "Game Info": "Spielinfo", "Game, Developer & Neem": "Spiel, Entwickler & Neem", "How Many Players": "Spieleranzahl", "AI Disclosure": "KI-Hinweis", Guides: "Guides", "Turn Off Flashlight": "Taschenlampe ausschalten", "Upgrade the Shop": "Shop verbessern", "How to Play": "Spielanleitung", Help: "Hilfe", "Spark Cannot Move": "Spark kann sich nicht bewegen", "Demo Not Working": "Demo funktioniert nicht", "Options & Settings": "Optionen & Einstellungen", Enemies: "Gegner", Community: "Community", "Wiki Resources": "Wiki-Ressourcen", "All Wiki Pages": "Alle Wiki-Seiten", Overview: "Übersicht", "View all": "Alle anzeigen", "Primary navigation": "Hauptnavigation", "Open navigation": "Navigation öffnen", "Close navigation": "Navigation schließen", Explore: "Entdecken", "Wiki index": "Wiki-Verzeichnis", "Fixes & settings": "Fehlerbehebung & Einstellungen", Languages: "Sprachen", Site: "Website", About: "Über uns", Contact: "Kontakt", Privacy: "Datenschutz", Disclaimer: "Haftungsausschluss", Official: "Offiziell", "Skip to content": "Zum Inhalt springen",
  },
  fr: {
    Home: "Accueil", Platforms: "Plateformes", "Purchase & PC": "Achat et PC", Price: "Prix", "Free to Play": "Gratuit", "Release Date": "Date de sortie", "System Requirements": "Configuration requise", Consoles: "Consoles", "Console Guide": "Guide consoles", "Game Info": "Infos du jeu", "Game, Developer & Neem": "Jeu, développeur et Neem", "How Many Players": "Nombre de joueurs", "AI Disclosure": "Déclaration sur l’IA", Guides: "Guides", "Turn Off Flashlight": "Éteindre la lampe", "Upgrade the Shop": "Améliorer la boutique", "How to Play": "Comment jouer", Help: "Aide", "Spark Cannot Move": "Spark ne bouge plus", "Demo Not Working": "Démo en panne", "Options & Settings": "Options et réglages", Enemies: "Ennemis", Community: "Communauté", "Wiki Resources": "Ressources du wiki", "All Wiki Pages": "Toutes les pages", Overview: "Vue d’ensemble", "View all": "Tout afficher", "Primary navigation": "Navigation principale", "Open navigation": "Ouvrir la navigation", "Close navigation": "Fermer la navigation", Explore: "Explorer", "Wiki index": "Index du wiki", "Fixes & settings": "Correctifs et réglages", Languages: "Langues", Site: "Site", About: "À propos", Contact: "Contact", Privacy: "Confidentialité", Disclaimer: "Mentions légales", Official: "Officiel", "Skip to content": "Aller au contenu",
  },
  es: {
    Home: "Inicio", Platforms: "Plataformas", "Purchase & PC": "Compra y PC", Price: "Precio", "Free to Play": "Gratis", "Release Date": "Fecha de lanzamiento", "System Requirements": "Requisitos del sistema", Consoles: "Consolas", "Console Guide": "Guía de consolas", "Game Info": "Información del juego", "Game, Developer & Neem": "Juego, desarrollador y Neem", "How Many Players": "Número de jugadores", "AI Disclosure": "Declaración de IA", Guides: "Guías", "Turn Off Flashlight": "Apagar la linterna", "Upgrade the Shop": "Mejorar la tienda", "How to Play": "Cómo jugar", Help: "Ayuda", "Spark Cannot Move": "El Spark no se mueve", "Demo Not Working": "La Demo no funciona", "Options & Settings": "Opciones y ajustes", Enemies: "Enemigos", Community: "Comunidad", "Wiki Resources": "Recursos de la Wiki", "All Wiki Pages": "Todas las páginas", Overview: "Resumen", "View all": "Ver todo", "Primary navigation": "Navegación principal", "Open navigation": "Abrir navegación", "Close navigation": "Cerrar navegación", Explore: "Explorar", "Wiki index": "Índice de la Wiki", "Fixes & settings": "Soluciones y ajustes", Languages: "Idiomas", Site: "Sitio", About: "Acerca de", Contact: "Contacto", Privacy: "Privacidad", Disclaimer: "Aviso legal", Official: "Oficial", "Skip to content": "Saltar al contenido",
  },
  "pt-br": {
    Home: "Início", Platforms: "Plataformas", "Purchase & PC": "Compra e PC", Price: "Preço", "Free to Play": "Grátis", "Release Date": "Data de lançamento", "System Requirements": "Requisitos do sistema", Consoles: "Consoles", "Console Guide": "Guia de consoles", "Game Info": "Informações do jogo", "Game, Developer & Neem": "Jogo, desenvolvedor e Neem", "How Many Players": "Número de jogadores", "AI Disclosure": "Divulgação de IA", Guides: "Guias", "Turn Off Flashlight": "Desligar a lanterna", "Upgrade the Shop": "Melhorar a loja", "How to Play": "Como jogar", Help: "Ajuda", "Spark Cannot Move": "Spark não se move", "Demo Not Working": "Demo não funciona", "Options & Settings": "Opções e configurações", Enemies: "Inimigos", Community: "Comunidade", "Wiki Resources": "Recursos da Wiki", "All Wiki Pages": "Todas as páginas", Overview: "Visão geral", "View all": "Ver tudo", "Primary navigation": "Navegação principal", "Open navigation": "Abrir navegação", "Close navigation": "Fechar navegação", Explore: "Explorar", "Wiki index": "Índice da Wiki", "Fixes & settings": "Soluções e configurações", Languages: "Idiomas", Site: "Site", About: "Sobre", Contact: "Contato", Privacy: "Privacidade", Disclaimer: "Aviso legal", Official: "Oficial", "Skip to content": "Ir para o conteúdo",
  },
  ru: {
    Home: "Главная", Platforms: "Платформы", "Purchase & PC": "Покупка и ПК", Price: "Цена", "Free to Play": "Бесплатная игра", "Release Date": "Дата выхода", "System Requirements": "Системные требования", Consoles: "Консоли", "Console Guide": "Гайд по консолям", "Game Info": "Об игре", "Game, Developer & Neem": "Игра, разработчик и Neem", "How Many Players": "Количество игроков", "AI Disclosure": "Раскрытие ИИ", Guides: "Гайды", "Turn Off Flashlight": "Выключить фонарь", "Upgrade the Shop": "Улучшить магазин", "How to Play": "Как играть", Help: "Помощь", "Spark Cannot Move": "Spark не двигается", "Demo Not Working": "Demo не работает", "Options & Settings": "Параметры и настройки", Enemies: "Враги", Community: "Сообщество", "Wiki Resources": "Ресурсы вики", "All Wiki Pages": "Все страницы", Overview: "Обзор", "View all": "Показать всё", "Primary navigation": "Основная навигация", "Open navigation": "Открыть навигацию", "Close navigation": "Закрыть навигацию", Explore: "Разделы", "Wiki index": "Указатель вики", "Fixes & settings": "Исправления и настройки", Languages: "Языки", Site: "Сайт", About: "О сайте", Contact: "Контакты", Privacy: "Конфиденциальность", Disclaimer: "Отказ от ответственности", Official: "Официальные ссылки", "Skip to content": "Перейти к содержанию",
  },
  ja: {
    Home: "ホーム", Platforms: "プラットフォーム", "Purchase & PC": "購入とPC", Price: "価格", "Free to Play": "無料プレイ", "Release Date": "発売日", "System Requirements": "システム要件", Consoles: "コンソール", "Console Guide": "コンソールガイド", "Game Info": "ゲーム情報", "Game, Developer & Neem": "ゲーム・開発元・Neem", "How Many Players": "プレイヤー人数", "AI Disclosure": "AI利用の開示", Guides: "ガイド", "Turn Off Flashlight": "懐中電灯を消す", "Upgrade the Shop": "ショップを強化", "How to Play": "遊び方", Help: "トラブル対処", "Spark Cannot Move": "Sparkが動けない", "Demo Not Working": "Demoが動かない", "Options & Settings": "オプションと設定", Enemies: "敵", Community: "コミュニティ", "Wiki Resources": "Wiki資料", "All Wiki Pages": "全Wikiページ", Overview: "概要", "View all": "すべて表示", "Primary navigation": "メインナビゲーション", "Open navigation": "ナビゲーションを開く", "Close navigation": "ナビゲーションを閉じる", Explore: "探す", "Wiki index": "Wiki索引", "Fixes & settings": "修正方法と設定", Languages: "言語", Site: "サイト", About: "このサイトについて", Contact: "お問い合わせ", Privacy: "プライバシー", Disclaimer: "免責事項", Official: "公式", "Skip to content": "本文へ移動",
  },
  ko: {
    Home: "홈", Platforms: "플랫폼", "Purchase & PC": "구매 및 PC", Price: "가격", "Free to Play": "무료 플레이", "Release Date": "출시일", "System Requirements": "시스템 요구 사항", Consoles: "콘솔", "Console Guide": "콘솔 가이드", "Game Info": "게임 정보", "Game, Developer & Neem": "게임, 개발사 및 Neem", "How Many Players": "플레이어 수", "AI Disclosure": "AI 사용 공개", Guides: "공략", "Turn Off Flashlight": "손전등 끄기", "Upgrade the Shop": "상점 업그레이드", "How to Play": "플레이 방법", Help: "문제 해결", "Spark Cannot Move": "Spark가 움직이지 않음", "Demo Not Working": "Demo가 작동하지 않음", "Options & Settings": "옵션 및 설정", Enemies: "적", Community: "커뮤니티", "Wiki Resources": "Wiki 자료", "All Wiki Pages": "모든 Wiki 페이지", Overview: "개요", "View all": "모두 보기", "Primary navigation": "기본 탐색", "Open navigation": "탐색 열기", "Close navigation": "탐색 닫기", Explore: "둘러보기", "Wiki index": "Wiki 색인", "Fixes & settings": "해결 방법 및 설정", Languages: "언어", Site: "사이트", About: "소개", Contact: "문의", Privacy: "개인정보", Disclaimer: "면책 조항", Official: "공식", "Skip to content": "본문으로 이동",
  },
  uk: {
    Home: "Головна", Platforms: "Платформи", "Purchase & PC": "Купівля та ПК", Price: "Ціна", "Free to Play": "Безкоштовна гра", "Release Date": "Дата виходу", "System Requirements": "Системні вимоги", Consoles: "Консолі", "Console Guide": "Гайд для консолей", "Game Info": "Про гру", "Game, Developer & Neem": "Гра, розробник і Neem", "How Many Players": "Кількість гравців", "AI Disclosure": "Відомості про ШІ", Guides: "Гайди", "Turn Off Flashlight": "Вимкнути ліхтар", "Upgrade the Shop": "Покращити магазин", "How to Play": "Як грати", Help: "Допомога", "Spark Cannot Move": "Spark не рухається", "Demo Not Working": "Demo не працює", "Options & Settings": "Параметри та налаштування", Enemies: "Вороги", Community: "Спільнота", "Wiki Resources": "Ресурси вікі", "All Wiki Pages": "Усі сторінки", Overview: "Огляд", "View all": "Показати все", "Primary navigation": "Основна навігація", "Open navigation": "Відкрити навігацію", "Close navigation": "Закрити навігацію", Explore: "Розділи", "Wiki index": "Покажчик вікі", "Fixes & settings": "Виправлення та налаштування", Languages: "Мови", Site: "Сайт", About: "Про сайт", Contact: "Контакти", Privacy: "Конфіденційність", Disclaimer: "Відмова від відповідальності", Official: "Офіційні посилання", "Skip to content": "Перейти до вмісту",
  },
};

const footerCopy: Record<ArticleLocale, { description: string; lastResearchPass: string; artwork: string }> = {
  en: { description: "An independent, evidence-led GRAIN ROT wiki. Not affiliated with Beck & Branch Games or Neem Interactive.", lastResearchPass: "Last research pass", artwork: "Game artwork © its respective owners." },
  de: { description: "Ein unabhängiges, quellenbasiertes GRAIN ROT Wiki. Nicht mit Beck & Branch Games oder Neem Interactive verbunden.", lastResearchPass: "Letzte Quellenprüfung", artwork: "Die Spielgrafiken gehören ihren jeweiligen Rechteinhabern." },
  fr: { description: "Un wiki GRAIN ROT indépendant fondé sur des sources. Sans affiliation avec Beck & Branch Games ou Neem Interactive.", lastResearchPass: "Dernière vérification", artwork: "Les visuels du jeu appartiennent à leurs ayants droit respectifs." },
  es: { description: "Una wiki independiente de GRAIN ROT basada en fuentes. No está afiliada con Beck & Branch Games ni Neem Interactive.", lastResearchPass: "Última revisión", artwork: "Las imágenes del juego pertenecen a sus respectivos propietarios." },
  "pt-br": { description: "Uma wiki independente de GRAIN ROT baseada em fontes. Sem afiliação com Beck & Branch Games ou Neem Interactive.", lastResearchPass: "Última revisão", artwork: "As imagens do jogo pertencem aos respectivos proprietários." },
  ru: { description: "Независимая вики GRAIN ROT с проверяемыми источниками. Не связана с Beck & Branch Games или Neem Interactive.", lastResearchPass: "Последняя проверка", artwork: "Права на материалы игры принадлежат их владельцам." },
  ja: { description: "情報源を明示する独立系GRAIN ROT Wikiです。Beck & Branch GamesおよびNeem Interactiveとは関係ありません。", lastResearchPass: "最終確認日", artwork: "ゲーム画像の権利は各権利者に帰属します。" },
  ko: { description: "출처를 바탕으로 운영하는 독립 GRAIN ROT Wiki입니다. Beck & Branch Games 또는 Neem Interactive와 관련이 없습니다.", lastResearchPass: "최근 자료 검토", artwork: "게임 이미지의 권리는 각 소유자에게 있습니다." },
  uk: { description: "Незалежна вікі GRAIN ROT із перевіреними джерелами. Не пов’язана з Beck & Branch Games або Neem Interactive.", lastResearchPass: "Остання перевірка", artwork: "Права на матеріали гри належать відповідним власникам." },
};

const evidenceCopy: Record<ArticleLocale, Record<EvidenceLevel, string>> = {
  en: { Official: "Official", "Official + community": "Official + community", "Community observed": "Community observed" },
  de: { Official: "Offiziell", "Official + community": "Offiziell + Community", "Community observed": "Von der Community beobachtet" },
  fr: { Official: "Officiel", "Official + community": "Officiel + communauté", "Community observed": "Observé par la communauté" },
  es: { Official: "Oficial", "Official + community": "Oficial + comunidad", "Community observed": "Observado por la comunidad" },
  "pt-br": { Official: "Oficial", "Official + community": "Oficial + comunidade", "Community observed": "Observado pela comunidade" },
  ru: { Official: "Официально", "Official + community": "Официально + сообщество", "Community observed": "Наблюдение сообщества" },
  ja: { Official: "公式", "Official + community": "公式 + コミュニティ", "Community observed": "コミュニティで確認" },
  ko: { Official: "공식", "Official + community": "공식 + 커뮤니티", "Community observed": "커뮤니티 관찰" },
  uk: { Official: "Офіційно", "Official + community": "Офіційно + спільнота", "Community observed": "Спостереження спільноти" },
};

export function getChromeLabel(locale: ArticleLocale, label: string) {
  return chromeLabels[locale][label] ?? label;
}

export function getFooterCopy(locale: ArticleLocale) {
  return footerCopy[locale];
}

export function getEvidenceLabel(locale: ArticleLocale, level: EvidenceLevel) {
  return evidenceCopy[locale][level];
}
