import type { EvidenceLevel } from "@/lib/content";
import type { ArticleLocale } from "@/lib/i18n";

const chromeLabels: Record<ArticleLocale, Record<string, string>> = {
  en: {},
  de: {
    Home: "Startseite", Platforms: "Plattformen", "Purchase & PC": "Kauf & PC", Price: "Preis", "Free to Play": "Kostenlos spielbar?", "Release Date": "Veröffentlichungsdatum", "System Requirements": "Systemanforderungen", Consoles: "Konsolen", "Console Guide": "Konsolen-Guide", "Xbox & Game Pass": "Xbox & Game Pass", "Game Info": "Spielinfos", "Game, Developer & Neem": "Spiel, Entwickler & Neem Interactive", "How Many Players": "Spielerzahl", "AI Disclosure": "Hinweis zum KI-Einsatz", Guides: "Guides", "Turn Off Flashlight": "Taschenlampe ausschalten", "Upgrade the Shop": "Shop verbessern", "How to Play": "Spielprinzip", Help: "Hilfe", "Spark Cannot Move": "Spark kann sich nicht bewegen", "Demo Not Working": "Demo funktioniert nicht", "Options & Settings": "Optionen & Einstellungen", Enemies: "Gegner", Community: "Community", "Wiki Resources": "Wiki-Ressourcen", "All Wiki Pages": "Alle Wiki-Seiten", Overview: "Übersicht", "View all": "Alle anzeigen", "Primary navigation": "Hauptnavigation", "Open navigation": "Navigation öffnen", "Close navigation": "Navigation schließen", Explore: "Entdecken", "Wiki index": "Wiki-Verzeichnis", "Fixes & settings": "Fehlerbehebung & Einstellungen", Languages: "Sprachen", Site: "Website", About: "Über dieses Wiki", Contact: "Kontakt", Privacy: "Datenschutz", Disclaimer: "Haftungsausschluss", Official: "Offizielle Links", "Skip to content": "Zum Inhalt springen",
  },
  fr: {
    Home: "Accueil", Platforms: "Plateformes", "Purchase & PC": "Achat et PC", Price: "Prix", "Free to Play": "Jeu gratuit ?", "Release Date": "Date de sortie", "System Requirements": "Configuration requise", Consoles: "Consoles", "Console Guide": "Guide consoles", "Xbox & Game Pass": "Xbox et Game Pass", "Game Info": "Infos du jeu", "Game, Developer & Neem": "Jeu, développeur et Neem Interactive", "How Many Players": "Nombre de joueurs", "AI Disclosure": "Déclaration sur l’IA", Guides: "Guides", "Turn Off Flashlight": "Éteindre la lampe torche", "Upgrade the Shop": "Améliorer la boutique", "How to Play": "Comment jouer", Help: "Aide", "Spark Cannot Move": "Spark ne bouge plus", "Demo Not Working": "La démo ne fonctionne pas", "Options & Settings": "Options et réglages", Enemies: "Ennemis", Community: "Communauté", "Wiki Resources": "Ressources du wiki", "All Wiki Pages": "Toutes les pages", Overview: "Vue d’ensemble", "View all": "Tout afficher", "Primary navigation": "Navigation principale", "Open navigation": "Ouvrir la navigation", "Close navigation": "Fermer la navigation", Explore: "Explorer", "Wiki index": "Index du wiki", "Fixes & settings": "Dépannage et réglages", Languages: "Langues", Site: "Site", About: "À propos", Contact: "Contact", Privacy: "Confidentialité", Disclaimer: "Clause de non-responsabilité", Official: "Liens officiels", "Skip to content": "Aller au contenu",
  },
  es: {
    Home: "Inicio", Platforms: "Plataformas", "Purchase & PC": "Compra y versión para PC", Price: "Precio", "Free to Play": "¿Es gratis?", "Release Date": "Fecha de lanzamiento", "System Requirements": "Requisitos del sistema", Consoles: "Consolas", "Console Guide": "Guía de consolas", "Xbox & Game Pass": "Xbox y Game Pass", "Game Info": "Información del juego", "Game, Developer & Neem": "Juego, desarrollador y Neem Interactive", "How Many Players": "Número de jugadores", "AI Disclosure": "Información sobre el uso de IA", Guides: "Guías", "Turn Off Flashlight": "Apagar la linterna", "Upgrade the Shop": "Mejorar la tienda", "How to Play": "Cómo jugar", Help: "Ayuda", "Spark Cannot Move": "El Spark no se mueve", "Demo Not Working": "La demo no funciona", "Options & Settings": "Opciones y configuración", Enemies: "Enemigos", Community: "Comunidad", "Wiki Resources": "Recursos de la wiki", "All Wiki Pages": "Todas las páginas", Overview: "Descripción general", "View all": "Ver todo", "Primary navigation": "Navegación principal", "Open navigation": "Abrir el menú de navegación", "Close navigation": "Cerrar el menú de navegación", Explore: "Explorar", "Wiki index": "Índice de la wiki", "Fixes & settings": "Soluciones y configuración", Languages: "Idiomas", Site: "Sitio", About: "Acerca del sitio", Contact: "Contacto", Privacy: "Privacidad", Disclaimer: "Aviso legal", Official: "Enlaces oficiales", "Skip to content": "Ir al contenido",
  },
  "pt-br": {
    Home: "Início", Platforms: "Plataformas", "Purchase & PC": "Compra e versão para PC", Price: "Preço", "Free to Play": "É gratuito?", "Release Date": "Data de lançamento", "System Requirements": "Requisitos do sistema", Consoles: "Consoles", "Console Guide": "Guia para consoles", "Xbox & Game Pass": "Xbox e Game Pass", "Game Info": "Informações do jogo", "Game, Developer & Neem": "Jogo, desenvolvedora e Neem Interactive", "How Many Players": "Número de jogadores", "AI Disclosure": "Transparência sobre o uso de IA", Guides: "Guias", "Turn Off Flashlight": "Desligar a lanterna", "Upgrade the Shop": "Melhorar a loja", "How to Play": "Como jogar", Help: "Ajuda", "Spark Cannot Move": "O Spark não se move", "Demo Not Working": "A demo não funciona", "Options & Settings": "Opções e configurações", Enemies: "Inimigos", Community: "Comunidade", "Wiki Resources": "Recursos da wiki", "All Wiki Pages": "Todas as páginas da wiki", Overview: "Visão geral", "View all": "Ver tudo", "Primary navigation": "Navegação principal", "Open navigation": "Abrir menu de navegação", "Close navigation": "Fechar menu de navegação", Explore: "Explorar", "Wiki index": "Índice da wiki", "Fixes & settings": "Correções e configurações", Languages: "Idiomas", Site: "Site", About: "Sobre a wiki", Contact: "Contato", Privacy: "Privacidade", Disclaimer: "Aviso legal", Official: "Links oficiais", "Skip to content": "Ir para o conteúdo",
  },
  ru: {
    Home: "Главная", Platforms: "Платформы", "Purchase & PC": "Покупка и версия для ПК", Price: "Цена", "Free to Play": "Можно играть бесплатно?", "Release Date": "Дата выхода", "System Requirements": "Системные требования", Consoles: "Консоли", "Console Guide": "Гайд по консольным версиям", "Xbox & Game Pass": "Xbox и Game Pass", "Game Info": "Об игре", "Game, Developer & Neem": "Игра, разработчик и Neem Interactive", "How Many Players": "Количество игроков", "AI Disclosure": "Об использовании ИИ", Guides: "Гайды", "Turn Off Flashlight": "Как выключить фонарь", "Upgrade the Shop": "Как улучшить магазин", "How to Play": "Как играть", Help: "Решение проблем", "Spark Cannot Move": "Spark не двигается", "Demo Not Working": "Демо-версия не запускается", "Options & Settings": "Настройки", Enemies: "Враги", Community: "Сообщество", "Wiki Resources": "Материалы вики", "All Wiki Pages": "Все страницы вики", Overview: "Обзор", "View all": "Показать всё", "Primary navigation": "Основная навигация", "Open navigation": "Открыть меню навигации", "Close navigation": "Закрыть меню навигации", Explore: "Разделы", "Wiki index": "Каталог вики", "Fixes & settings": "Решение проблем и настройки", Languages: "Языки", Site: "Сайт", About: "О сайте", Contact: "Контакты", Privacy: "Политика конфиденциальности", Disclaimer: "Отказ от ответственности", Official: "Официальные ссылки", "Skip to content": "Перейти к содержанию",
  },
  ja: {
    Home: "ホーム", Platforms: "プラットフォーム", "Purchase & PC": "購入・PC版", Price: "価格", "Free to Play": "無料で遊べる？", "Release Date": "発売日", "System Requirements": "動作環境", Consoles: "コンソール版", "Console Guide": "コンソール版ガイド", "Xbox & Game Pass": "Xbox／Game Pass", "Game Info": "ゲーム情報", "Game, Developer & Neem": "ゲーム・開発元・Neem Interactive", "How Many Players": "プレイ人数", "AI Disclosure": "AI使用に関する開示", Guides: "攻略ガイド", "Turn Off Flashlight": "懐中電灯を消す方法", "Upgrade the Shop": "ショップの強化方法", "How to Play": "遊び方", Help: "トラブル解決", "Spark Cannot Move": "Sparkが動かない", "Demo Not Working": "体験版が起動しない", "Options & Settings": "オプション・設定", Enemies: "敵", Community: "コミュニティ", "Wiki Resources": "Wiki関連情報", "All Wiki Pages": "Wiki全ページ", Overview: "概要", "View all": "すべて見る", "Primary navigation": "メインナビゲーション", "Open navigation": "ナビゲーションを開く", "Close navigation": "ナビゲーションを閉じる", Explore: "コンテンツ", "Wiki index": "Wikiページ一覧", "Fixes & settings": "不具合対処・設定", Languages: "言語", Site: "サイト情報", About: "このWikiについて", Contact: "お問い合わせ", Privacy: "プライバシーポリシー", Disclaimer: "免責事項", Official: "公式リンク", "Skip to content": "本文へ移動",
  },
  ko: {
    Home: "홈", Platforms: "플랫폼", "Purchase & PC": "구매 및 PC판", Price: "가격", "Free to Play": "무료 플레이 여부", "Release Date": "출시일", "System Requirements": "시스템 요구 사항", Consoles: "콘솔", "Console Guide": "콘솔 가이드", "Xbox & Game Pass": "Xbox 및 Game Pass", "Game Info": "게임 정보", "Game, Developer & Neem": "게임, 개발사 및 Neem Interactive", "How Many Players": "플레이어 수", "AI Disclosure": "AI 사용 안내", Guides: "공략", "Turn Off Flashlight": "손전등 끄기", "Upgrade the Shop": "상점 업그레이드", "How to Play": "플레이 방법", Help: "문제 해결", "Spark Cannot Move": "Spark가 움직이지 않음", "Demo Not Working": "데모가 실행되지 않음", "Options & Settings": "옵션 및 설정", Enemies: "적", Community: "커뮤니티", "Wiki Resources": "Wiki 자료", "All Wiki Pages": "모든 Wiki 페이지", Overview: "개요", "View all": "모두 보기", "Primary navigation": "주 메뉴", "Open navigation": "메뉴 열기", "Close navigation": "메뉴 닫기", Explore: "둘러보기", "Wiki index": "위키 문서 목록", "Fixes & settings": "해결 방법 및 설정", Languages: "언어", Site: "사이트", About: "소개", Contact: "문의", Privacy: "개인정보 처리방침", Disclaimer: "면책 조항", Official: "공식 링크", "Skip to content": "본문으로 이동",
  },
  uk: {
    Home: "Головна", Platforms: "Платформи", "Purchase & PC": "Купівля та ПК", Price: "Ціна", "Free to Play": "Чи можна грати безкоштовно?", "Release Date": "Дата виходу", "System Requirements": "Системні вимоги", Consoles: "Консолі", "Console Guide": "Гайд для консолей", "Xbox & Game Pass": "Xbox і Game Pass", "Game Info": "Про гру", "Game, Developer & Neem": "Гра, розробник і Neem Interactive", "How Many Players": "Кількість гравців", "AI Disclosure": "Відомості про ШІ", Guides: "Гайди", "Turn Off Flashlight": "Вимкнути ліхтар", "Upgrade the Shop": "Покращити магазин", "How to Play": "Як грати", Help: "Допомога", "Spark Cannot Move": "Spark не рухається", "Demo Not Working": "Демоверсія не працює", "Options & Settings": "Налаштування гри", Enemies: "Вороги", Community: "Спільнота", "Wiki Resources": "Ресурси вікі", "All Wiki Pages": "Усі сторінки", Overview: "Огляд", "View all": "Показати все", "Primary navigation": "Основна навігація", "Open navigation": "Відкрити навігацію", "Close navigation": "Закрити навігацію", Explore: "Розділи", "Wiki index": "Каталог вікі", "Fixes & settings": "Розв’язання проблем і налаштування", Languages: "Мови", Site: "Сайт", About: "Про сайт", Contact: "Контакти", Privacy: "Конфіденційність", Disclaimer: "Відмова від відповідальності", Official: "Офіційні посилання", "Skip to content": "Перейти до вмісту",
  },
};

const footerCopy: Record<ArticleLocale, { description: string; lastResearchPass: string; artwork: string }> = {
  en: { description: "An independent, evidence-led GRAIN ROT wiki. Not affiliated with Beck & Branch Games or Neem Interactive.", lastResearchPass: "Last research pass", artwork: "Game artwork © its respective owners." },
  de: { description: "Ein unabhängiges Wiki zu GRAIN ROT mit geprüften Quellen. Nicht mit Beck & Branch Games oder Neem Interactive verbunden.", lastResearchPass: "Letzte Quellenprüfung", artwork: "Die Rechte an den Spielgrafiken liegen bei den jeweiligen Rechteinhabern." },
  fr: { description: "Un wiki indépendant consacré à GRAIN ROT, qui s’appuie sur des sources vérifiables. Sans affiliation avec Beck & Branch Games ni Neem Interactive.", lastResearchPass: "Dernière vérification des sources", artwork: "Les visuels du jeu appartiennent à leurs ayants droit respectifs." },
  es: { description: "Una wiki independiente sobre GRAIN ROT, basada en fuentes verificables. No está afiliada a Beck & Branch Games ni a Neem Interactive.", lastResearchPass: "Última revisión de fuentes", artwork: "Los derechos de las imágenes del juego pertenecen a sus respectivos titulares." },
  "pt-br": { description: "Uma wiki independente de GRAIN ROT baseada em fontes verificáveis. Não possui vínculo com a Beck & Branch Games nem com a Neem Interactive.", lastResearchPass: "Última verificação das fontes", artwork: "Os direitos das imagens do jogo pertencem aos respectivos titulares." },
  ru: { description: "Независимая вики по GRAIN ROT, основанная на проверяемых источниках. Не связана с Beck & Branch Games или Neem Interactive.", lastResearchPass: "Последняя проверка источников", artwork: "Права на изображения из игры принадлежат соответствующим правообладателям." },
  ja: { description: "出典の確認を重視する、GRAIN ROTの独立系Wikiです。Beck & Branch GamesおよびNeem Interactiveとは関係ありません。", lastResearchPass: "最終情報確認日", artwork: "ゲーム内画像の著作権は、それぞれの権利者に帰属します。" },
  ko: { description: "검증 가능한 출처를 바탕으로 한 독립 GRAIN ROT 위키입니다. Beck & Branch Games 및 Neem Interactive와 제휴 관계가 없습니다.", lastResearchPass: "최근 자료 검토일", artwork: "게임 이미지의 저작권은 각 권리자에게 있습니다." },
  uk: { description: "Незалежна вікі GRAIN ROT, що спирається на перевірені джерела. Не пов’язана з Beck & Branch Games чи Neem Interactive.", lastResearchPass: "Остання перевірка джерел", artwork: "Права на зображення з гри належать відповідним правовласникам." },
};

const evidenceCopy: Record<ArticleLocale, Record<EvidenceLevel, string>> = {
  en: { Official: "Official", "Official + community": "Official + community", "Community observed": "Community observed" },
  de: { Official: "Offiziell", "Official + community": "Offiziell + Community", "Community observed": "Von der Community beobachtet" },
  fr: { Official: "Source officielle", "Official + community": "Sources officielles et communauté", "Community observed": "Observation de la communauté" },
  es: { Official: "Información oficial", "Official + community": "Información oficial y de la comunidad", "Community observed": "Observación de la comunidad" },
  "pt-br": { Official: "Fonte oficial", "Official + community": "Fontes oficiais e da comunidade", "Community observed": "Observação da comunidade" },
  ru: { Official: "Официальные источники", "Official + community": "Официальные источники + сообщество", "Community observed": "По наблюдениям сообщества" },
  ja: { Official: "公式情報", "Official + community": "公式情報＋コミュニティ", "Community observed": "コミュニティでの観察報告" },
  ko: { Official: "공식 정보", "Official + community": "공식 정보 + 커뮤니티", "Community observed": "커뮤니티 관찰 내용" },
  uk: { Official: "Офіційні джерела", "Official + community": "Офіційні джерела + спільнота", "Community observed": "За спостереженнями спільноти" },
};

export function getChromeLabel(locale: ArticleLocale, label: string) {
  return chromeLabels[locale][label] ?? label;
}

export function getFooterCopy(locale: ArticleLocale) {
  return footerCopy[locale];
}

export function getEvidenceLabel(locale: ArticleLocale, level: EvidenceLevel) {
  return evidenceCopy[locale][level];
}
